### PR TITLE
Implement XML configuration loader

### PR DESCRIPTION
**Pull request by lucko**
Implements #57

### CODE REVIEW

**Comment by lucko** [comment]
This is no longer WIP.

I'd welcome any feedback / comments.

**Comment by FerusGrim** [comment]
I had given up hope. I'm in love with you @lucko <3

**Comment by lucko** [comment]
Bump - any update on the status of this?

**Comment by kashike** [comment]
I'd want to see this merged after #92.

**Comment by Meronat** [comment]
Can you update this with the other changes, as well as style changes you previously made?

**Comment by lucko** [comment]
I've rebased this against master and updated the style to match the other changes.

I've also fixed an issue with the way lists were serialised, and added a few more tests. Should be good to be reviewed/merged now. :)

**Comment by Meronat** [comment]
I will give this a look soon, but I'd also like to see @zml2008's feedback as this is a fairly large change, adding a completely new loader.

**Comment by XakepSDK** [comment]
Whilst pr is ok, but XML map/list impl. is wrong. There is no schema and namespace for you map/list, this is really bad.
Every xml file(since xml 1.1) must start with xml header.
https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-prolog-dtd
Also, attributes may be not just strings, but enums or sets of tokenized types.
https://www.w3.org/TR/xml11/#attdecls

https://www.w3.org/XML/Core/#Publications

**Comment by lucko** [comment]
Thanks for your feedback.

> map/list types are made wrong, they re must be namespaced and must have schema.

Could you elaborate a bit more on exactly what you mean by this? I don't really understand what you're talking about.

> Every xml file(since xml 1.1) must start with xml header.

The loader already had the option to include the header, I've now set it to be enabled by default. Thanks :)

> Also, attributes may be not just strings, but enums or sets of tokenized types.

The page you linked doesn't make much sense to me. The native Java library being used for parsing doesn't seem to support anything other than String-String pairs for attributes.

https://docs.oracle.com/javase/7/docs/api/org/w3c/dom/Attr.html

> Also, you don't handle XML comments system.

I've implemented an appropriate comment handler now and added a test.

**Comment by XakepSDK** [comment]
1. Ok, just skip it
2. Does your comments impl. allow me to write multi-line comments like this:
```
<!--
My multiline
comment here
-->
If no, impl is wrong.

**Comment by lucko** [comment]
No, the comment handler forms comments like this

```
<!--
 ~ My multiline
 ~ comment here
 -->
```

It will still correctly parse your example

**Comment by FerusGrim** [comment]
@lucko Still looking forward to this being merged! Are there any concerns besides the issues brought forth by @XakepSDK ?

Additionally, it looks as if the project has been switched over to Gradle, causing some issues as this PR was started when it was still using Maven. <3

**Comment by lucko** [comment]
Yea, will need to be rebased.

I'm not sure what the status is, I would prefer to gather more feedback / approval from people before this is merged though.

**Comment by lucko** [comment]
It's rebased now, so can be merged when ready.

I've also added a few more tests.

**Comment by bloodmc** [comment]
@Meronat Please review so we can get this merged.

**Comment by kashike** [comment]
Thanks, @lucko.

**Pull request merged**
