### PR TITLE
Reflect Maven to Gradle changes in README.md

### PR DESCRIPTION
**Pull request by FerusGrim**
1. Update reference from Maven to Gradle
2. Update instructions on how to build and where artifacts are, afterwards, located
3. In **Usage**, move the Gradle block atop the Maven block. Because we can.

### CODE REVIEW

**Comment by FerusGrim** [comment]
Please feel free to ignore the fact that the sole commit to this PR flips Maven to Gradle.

**Comment by lucko** [comment]
Should reflect usage of the Gradle wrapper


aka `gradlew` instead of `gradle`

**Comment by lucko** [comment]
Might additionally be worth making all of the wording here consistent with other Sponge projects

e.g. https://github.com/SpongePowered/SpongeAPI#clone

**Comment by FerusGrim** [comment]
@lucko Done. :) 

A few differences from other Sponge projects:

1. Disregarded the typical "step 3" of cloning, because the `pre-push` is specifically for developers pushing to repositories.
2. Specified that the `./build/libs` folder is located in _each_ subproject, rather than the root directory.
3. Specified that the built JAR file would be `configurate-subproject-x.x-SNAPSHOT.jar` rather than without the subproject.

The only change I could anticipated being requested after this is to someone better identify `subproject`, but that seems likely excessive.

Let me know. :)

**Comment by dbrownidau** [comment]
Thanks for helping me with this one @FerusGrim :)

**Comment by FerusGrim** [comment]
@dbrownidau 🤡

**Pull request merged**
