### PR TITLE
Fix for #108

### PR DESCRIPTION
**Pull request by XakepSDK**
Custom predicates must follow this behaviour.
Fixes https://github.com/SpongePowered/configurate/issues/108

### CODE REVIEW

**Comment by dualspiral** [comment]
This is a break in current behaviour and will break expectations of consumers. There may be instances where first matching is desired. I admit, I don't have an example to hand, though I can envisage be that you might a subclass that you only want to serialise the super class for.

As a behaviour break, I strongly suggest that this only becomes a default, if at all, in 4.0, rather than 3.x.

In any case, I would much rather see this implemented as a series of options that can be applied. Maybe `TypeSerializerCollection.newChild` could have an overload (or a builder could be made) where such a selection rule can be set?

**Comment by XakepSDK** [comment]
Order sensitivity isn't documented anywhere.

**Comment by dualspiral** [comment]
And? It's still a behaviour change which has been based on the fact that configurate has been out there a while and therefore other systems that use it may be reliant on that fact.

**Comment by XakepSDK** [comment]
Ok. It's impossible to manage search order, if i add `Collection` serializer, i should re-implement Set and List serializer, because `Collection` serializer will take advantage.
We should talk about it.

**Comment by XakepSDK** [comment]
Reopening this because of this: https://github.com/SpongePowered/configurate/issues/110

**Comment by lucko** [comment]
It's expected that the first match will be used. If you want the `Set` serializer to take priority over the `Collection` one, you just need to ensure that it is registered first.

#110 is an unrelated issue.

**Pull request closed without merging**
