### PR TITLE
Addresses SpongePowered/configurate#131

### PR DESCRIPTION
**Pull request by MrZoraman**

### CODE REVIEW

**Comment by XakepSDK** [comment]
This PR silently breaks `Number` class subclasses like BigInteger, BigDecimal

**Comment by randombyte-developer** [comment]
Btw that's how I recently made a BigDecimal type serializer: https://github.com/randombyte-developer/taxation/blob/master/src/main/kotlin/de/randombyte/taxation/config/BigDecimalTypeSerializer.kt
The serialization of the underlying BigInteger could be extracted into its own type serializer too.

**Comment by MrZoraman** [comment]
Ah, I figured the Number class was fair game since it's already [supported ](https://github.com/SpongePowered/configurate/blob/9c2bdc73dd5a253794b7596f6d8cfd4dd06eb5bb/configurate-xml/src/main/java/ninja/leaping/configurate/xml/XMLConfigurationLoader.java#L418) by the xml backend. I'll look at those other classes later today.

**Comment by Asherslab** [comment]
Hi there @MrZoraman, has there been any progress on this? Could really use this

**Comment by zml2008** [comment]
Due to the changes to number serializers in 4.0, and because of the issues noted in #131, i'll be closing this PR. Changes to SpongeForge and configurate over the next little while should resolve the underlying issues leading to these changes.

**Pull request closed without merging**
