### PR TITLE
core: Switch functional types to using coffee

### PR DESCRIPTION
**Pull request by zml2008**

### CODE REVIEW

**Comment by dualspiral** [comment]
I’m not really sure why this change is needed. For things like `CheckedConsumer` where you’ve defined it yourself, okay (though I think that name is clearer than `Consumer1E`), but changing from the built in `Supplier` to `Function0` is just pointless if you ask me - unless there is a clear defined benefit to using a library type, why aren’t we preferring the standard JDK types which most, if not all, are a lot more familiar with?

**Comment by zml2008** [comment]
So the original impetus for this change was that the throwing variants of functional types felt generic enough that they should be in a separate library, rather than the ad-hoc collection configurate had -- and it turned out kashike had something similar he was willing to break out, so `coffee` (all ~15kb of it) was born.

I was originally skeptical of duplicating JDK function types, kashike eventually convinced me that the consistent naming scheme (`<type><input count><E (for exception-throwing) or none>`) and extra helper functions (for currying, memoizing, etc) would be useful enough, and only really possible by having a full functional type system.

This change is mostly user-invisible as well -- you can write lambdas as you normally would, and type inference will resolve to the new type, so the changes to most codebases are quite small.

**Comment by gabizou** [comment]
Sorry, why do we need yet another functional library, when there’s one already well established at providing a near full functional programming suite of things, including these <operation><count> types https://www.vavr.io/vavr-docs/#_functions

**Comment by dualspiral** [comment]
> consistent naming scheme

People are _already_ used to the JDK names - they make sense to them. In that, using such a library like this _isn't_ consistent with the standard library which is what people currently use and (somewhat?) understand. I will admit my own preference is for verbosity for user facing APIs - in that `CheckedSupplier` (for example) is more likely to be understood at a glance than `Function0E` because people know what a supplier is. `E` doesn't really convey that at a glance. Additionally, given `Function1` will likely extend `Function`, why should we be forcing people to use `Function1` instead of `Function` if, for some reason, they store the lambda or otherwise concrete class? Same for `Suppler` and `Function0`?

> and extra helper functions (for currying, memoizing, etc) would be useful enough

I'm not convinced about that in the context of what Configurate is doing - where would these be used? I'd be keeping the standard JDK types where possible, such that it is _possible_ to use these types if the user wishes to. All you're doing is swapping out one type for another that does the same thing with additional default methods, meaning that if I create a class that would implement `Consumer<>` whatever, I now need to change that.

> Sorry, why do we need yet another functional library, when there’s one already well established at providing a near full functional programming suite of things, including these types https://www.vavr.io/vavr-docs/#_functions

The real question here is does Configurate really need to depend on a library for this full stop? I'm just failing to see the benefit that any of this will bring (I'm not talking about FP here - if vavr was used in impl, sure, but all I'm really seeing here is signature changes away from the JDK types and the removal of three or so interfaces to use a library to supply interfaces.

**Review by kashike — APPROVED** [review]

**Comment by zml2008** [comment]
At this point, I think a 5.0.0 is infeasible given the magnitude of potential changes and existing adoption of the library, so there is no path forward for this PR.

**Pull request closed without merging**
